version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  # mongodb:
  #   image: mongo:latest
  #   container_name: mongodb
  #   ports:
  #     - "27017:27017"  # Bind to all interfaces for inter-container access
  #   volumes:
  #     - mongo-data:/data/db

  destni_user:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: destni_user
    ports:
      - "3001:3001" # Adjust the port as per your application
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_URI=mongodb://mongodb:27017/Destni_user
    depends_on:
      - redis
      # - mongodb

# volumes:
#   mongo-data:
